### ISSUE TITLE
test.py?

### ISSUE THREAD

**Issue by munaalsulaiti** [asbudhkar/ANN-PSO#1]
Hello,
I would like to know how to run the test.py properly? I get an error of stopiteration

**Comment by asbudhkar** [comment]
Please send me the error details.

**Comment by munaalsulaiti** [comment]
I want to write my own activation function. Can you please guide me on where to change that?

**Comment by asbudhkar** [comment]
Check the layers.py file

**Comment by munaalsulaiti** [comment]
coool, I found it. thank you soo much!!
